baseURL = "https://orefs.com/"
# ç½‘ç«™ meta æ•°æ®ä¸­å£°æ˜çš„è¯­è¨€
languageCode = "zh-CN"
# ç½‘ç«™é¢„è®¾æ–‡å­—å®é™…ä½¿ç”¨çš„è¯­è¨€
DefaultContentLanguage = "zh-cn"
title = "O Refs"
theme = "hugo-theme-stack"

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[Params]
description = 'åˆ†äº«ä¸€åˆ‡å¥½ä¸œè¥¿ã€‚'
rssFullContent = true
# åœ¨ç«™ç‚¹ /static ä¸‹
favicon = '/favicon.png'

[Params.DateFormat]
published = "2006-01-02 15:04"
lastUpdated = "2006-01-02 15:04"

[Params.Sidebar]
# ç´§å‡‘çš„ä¾§è¾¹æ 
compact = false
# å¤´åƒå³ä¸‹è§’æ˜¾ç¤ºçš„ emoji
emoji = ""
# ç½‘ç«™æ ‡é¢˜ä¸‹çš„å‰¯æ ‡é¢˜
subtitle = "åˆ†äº«ä¸€åˆ‡å¥½ä¸œè¥¿ ğŸ"

# æ˜¯å¦æ˜¾ç¤ºå¤´åƒ
avatar.enabled = true
# å¤´åƒæ–‡ä»¶è·¯å¾„ï¼Œåœ¨ç«™ç‚¹ /assets ä¸‹
avatar.src = "/img/avatar.png"

[Params.Footer]
since = 2024
customText = "ç”¨ â¤ï¸ åˆ†äº«ï¼Œä¿æŒçƒ­çˆ±"

[Params.Article]
license.enabled = true
license.default = "æ ¹æ® CC BY-NC-SA 4.0 è®¸å¯åè®®æˆæƒ"

[params.imageProcessing]
cover.enabled = true